### ISSUE TITLE
"Default Zoom" setting would be handy

### ISSUE THREAD

**Issue by gruthen** [nagata-yoshiteru/ppm-pgm-viewer-for-vscode#14]
Great Extension!

I'm using it with very small images and it gets annoying having to zoom in on each one. Would be great if someone can add a "Default Zoom" to the settings. Or perhaps an "Auto-zoom" so that small images are rendered to fit the available space.

**Comment by nagata-yoshiteru** [comment]
Thank you for using our extention!

As you proposed, I added a config to set default zoom level in #16 .
I will publish this update after code review.

Thanks!

**Comment by nagata-yoshiteru** [comment]
We added "Default Zoom" and "Auto Scaling" feature in above PR!
We will release new version soon!
Thanks!
