### ISSUE TITLE
"UI Position" setting would be handy

### ISSUE THREAD

**Issue by gruthen** [nagata-yoshiteru/ppm-pgm-viewer-for-vscode#15]
Great extension!

Would be great if the UI could be drawn on the RHS (so that when sharing screen-grabs that include the image title the big red UI is out-of-view).

**Comment by nagata-yoshiteru** [comment]
Hi @gruthen !

I also opend new PR #17 !
If you have any comment for #16 and #17, please feel free to leave!

Thanks!

**Comment by nagata-yoshiteru** [comment]
Hi @gruthen !

We merged #17 and will release new version in few days.

Thanks!
